using Admission.Application.Common.Messaging.IntegrationEvent.BaseEvents;

namespace Admission.Application.Common.Messaging.IntegrationEvent.Events.DocumentType;

public sealed class DocumentDeleteTimeChangedIntegrationEvent: DeleteTimeChangedIntegrationEvent;