using Admission.DTOs.IntegrationEvents.BaseEvents;

namespace Admission.DTOs.IntegrationEvents.Events.EducationProgram;

public sealed class ProgramDeleteTimeChangedIntegrationEvent: DeleteTimeChangedIntegrationEvent;