using Admission.Application.Common.Messaging.IntegrationEvent.BaseEvents;

namespace Admission.Application.Common.Messaging.IntegrationEvent.Events.NextEducationLevel;

public sealed class NextLevelDeleteTimeChangedIntegrationEvent: DeleteTimeChangedIntegrationEvent;